### ISSUE TITLE
Issue with player heads

### ISSUE THREAD

**Issue by HgeX** [Hazebyte/CrateReloaded#434] opened 2020-01-12 11:51 UTC
This one is a bit complicated, but I'll try my best to explain it. I have a server running on **Paper-167** *(MC 1.14.4)*, and the issue is present if I join using a client 1.13 or below (so the issue is might as well caused by ViaBackwards, I'm not sure :/).

Let's say I have a crate called `test`. I link it to a chest for instance (but really every block should work just fine exept player heads). Then I click on it with a `test` key, that sould open the crate, and it works. However, if the crate is linked to a player head instead *(which looks absolutely amazing btw)*, the result is different. If I hold the key in my hand, nothing happens at all, but if I have it in the hotbar but not in my hand, the plugins says that I don't have the appropriate key if I'm in survival or adventure mode, otherwise the crate opens.

Hope my explanation is somewhat clear, if not, please let me know!

**Comment by imWillX** [comment] 2020-01-30 06:16
Thanks for reporting this issue. Unfortunately, if it is an issue caused by ViaBackwards or ViaForwards, I won't be looking into these. The keys should work on player heads if you are running the client on the same version.

**Comment by HgeX** [comment] 2020-01-30 08:05
Honestly I'm really not sure about this bug and it's source. Should I report this to ViacBack instead?

**Comment by imWillX** [comment] 2020-07-27 07:09
Closing. Reopen if there are any issues.

**Closed by imWillX** 2020-07-27 07:09 UTC
