### ISSUE TITLE
[Suggestion] Display Item Read Command

### ISSUE THREAD

**Issue by NolanMC** [Hazebyte/CrateReloaded#210] opened 2018-03-20 15:55 UTC
So I have seen something similar to this in another plugin, where basically you hold an item in your hand and the command will print out how the item would be configured within the plugin. I think something like this would be a really good addition in case people have display items that would be inconvenient to reproduce. 

Steps on How this would work:
1. Hold item in hand
2. Type something like /cr read or /cr itemread
3. Display Item configuration would print to a file in the plugin folder. 

Note: This could also work for rewards if you are giving rewards using the item function within your crates.yml (I don't personally).

**Comment by XXLuigiMario** [comment] 2018-03-20 16:08
Duplicate of #204, please see https://github.com/Hazebyte/CrateReloadedAPI/issues/25 for information on this topic.

**Closed by XXLuigiMario** 2018-03-20 16:08 UTC
Labels: duplicate
