### ISSUE TITLE
Crate Reload Bug

### ISSUE THREAD

**Issue by Tomographix** [Hazebyte/CrateReloaded#283] opened 2018-08-11 02:49 UTC
Hi on typing /cr reload will frequently get this error.

`11.08 12:41:23 [Server] INFO [CrateReloaded] Config Version: 2.X
11.08 12:41:23 [Server] WARN [CrateReloaded] Error occured while executing command crate
11.08 12:41:23 [Server] INFO I'm sorry, but there was an error performing this command.
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF] Exception in command: crate reload
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF] java.lang.reflect.InvocationTargetException
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at java.lang.reflect.Method.invoke(Method.java:498)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at com.hazebyte.acf.RegisteredCommand.invoke(RegisteredCommand.java:147)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at com.hazebyte.acf.BaseCommand.executeCommand(BaseCommand.java:651)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at com.hazebyte.acf.BaseCommand.execute(BaseCommand.java:494)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at com.hazebyte.acf.RootCommand.execute(RootCommand.java:67)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at com.hazebyte.acf.BukkitRootCommand.execute(BukkitRootCommand.java:62)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:723)
11.08 12:41:23 [Server] ERROR [CrateReloaded] [ACF]     at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchServerCommand(CraftServer.java:685)
11.08 12:41:24 [Multicraft] Skipped 58 lines due to rate limit (30/s)`

Unfortunately provides little info to be able to trouble shoot.
This server is running Paper version git-Paper-110 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by ProfCube** [comment] 2018-08-11 03:40
Add on to this Bug, found that for 1.13. Everything is support delicate when editing the crate.yml 
**Example:**
```PARTYKey:
    type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'TRIPWIRE_HOOK 1 name:&c&l●_&d&lFRUITPARTY_&c&l●&7 lore:&dThank_you_for_voting!|&dUse_at_/warp_crates glow:true'
    animation: 'CSGO'
    display-name: '&c&l● &d&lFRUITPARTY &c&l●&7'
    holographic:
        - '&c&l● &d&lFRUITPARTY &c&l●&7'
    confirmation:
        enabled: true
        accept-button: 'STAINED_GLASS_PANE:5 1 name:&a&lYes lore:&6Click_here_to_open_&c&l●_&d&lFRUITPARTY_&c&l●&7'
        decline-button: 'STAINED_GLASS_PANE:14 1 name:&4&lNo lore:&6Click_to_not_open_a_&c&l●_&d&lFRUITPARTY_&c&l●&7'
    preview:
        enabled: true
        rows: 2
    buy:
        enabled: false
        cost: 0
    message:
        open: '&a&l{player} &aYou have opened a &6&o{crate} Crate'
        broadcast: '&c&l● &d{player} &dhas opened a &6&o{crate} &dand received {item}!'
    effect:
        1:
          class: Original
          category: PERSISTENT
          particle: SPELL_WITCH
        2:
          class: Sound
          category: ANIMATION
          sound: BLOCK_WOOD_PLACE
        3:
          class: Sound
          sound: ENTITY_PLAYER_LEVELUP
          CATEGORY: END
        4:
          class: Firework
          fireworkType: BALL
          color: PURPLE
          color: PINK
          color: BLACK
    reward:
        minimum-rewards: 1
        maximum-rewards: 1
        rewards:
            - 'unique:(),     chance:(10),         item:(DIAMOND_PICKAXE 1 &dWorld-Breaker &dSmash! 34:4 32:5)'
```
The part where is `item:(DIAMOND_PICKAXE 1 &dWorld-Breaker &dSmash! 34:4 32:5)'` were it's giving a False Parsing **ERROR** in the console. But when I do this `item:(DIAMOND_PICKAXE 1 &dWorld-Breaker &dSmash! 34:4 32:5), display:(DIAMOND_PICKAXE 1 name:&dWorld-Breaker lore:&dSmash! 34:4 32:5)'`It Fully destroy the plugin from working at all, just by adding the enchantments at the end of the display. Anything else like removing the Enchantments it will work fine.

**Comment by mibby** [comment] 2018-08-13 11:43
@imWillX I'm able to confirm this happens on 1.12.2 too.

CrateReloaded Premium v2.0-alpha7
Paper dev 1536 (Spigot 1.12.2)
```
[04:41:19] [Server thread/INFO]: mibby issued server command: /cr reload
[04:41:19] [Server thread/WARN]: [CrateReloaded] Error occured while executing command crate
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] Exception in command: crate reload 
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] java.lang.reflect.InvocationTargetException
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at com.hazebyte.acf.RegisteredCommand.invoke(RegisteredCommand.java:147)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at com.hazebyte.acf.BaseCommand.executeCommand(BaseCommand.java:651)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at com.hazebyte.acf.BaseCommand.execute(BaseCommand.java:494)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at com.hazebyte.acf.RootCommand.execute(RootCommand.java:67)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at com.hazebyte.acf.BukkitRootCommand.execute(BukkitRootCommand.java:62)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1475)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1280)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at java.lang.Thread.run(Thread.java:748)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] Caused by: java.lang.NullPointerException
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at cratereloaded.i.o(ClaimManager.java:47)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at cratereloaded.i.cleanup(ClaimManager.java:88)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at com.hazebyte.crate.cratereloaded.CorePlugin.onDisable(CorePlugin.java:297)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at com.hazebyte.crate.cratereloaded.CorePlugin.reloadAll(CorePlugin.java:98)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	at cratereloaded.l.b(CrateCommand.java:53)
[04:41:19] [Server thread/ERROR]: [CrateReloaded] [ACF] 	... 24 more
```

**Comment by imWillX** [comment] 2018-08-22 02:54
Wasn't able to reproduce but added checks to `2.0-alpha8`

**Comment by imWillX** [comment] 2018-08-22 02:59
Fix will be released in `alpha8`. This is due to disabling the message task.

**Closed by imWillX** 2018-08-22 02:59 UTC

**Comment by mibby** [comment] 2018-08-24 15:15
@imWillX When do you think ```alpha8``` will be released?
