### ISSUE TITLE
Mysterycrates not taking crate item after reward

### ISSUE THREAD

**Issue by doitliketyler** [Hazebyte/CrateReloaded#574] opened 2022-10-02 23:29 UTC
I have some msyterycrates setup and sometimes when a player uses them the plugin doesn't take the crate item away and the player can just keep right-clicking to get more and more rewards until the plugin finally decides to take the crate item away. I've had to completely disable them due to this. Any chance you can take a look into this and send out a fix?

I'm have the latest version of the plugin and I'm on Purpur 1.19.2. Thanks in advance.

**Comment by imWillX** [comment] 2022-10-03 02:26
@doitliketyler Need more information. 

1. Can you provide a gif? 
2. What plugins are you using? 
3. How often does this happen?
4. What plugin version are you running?

This seems difficult to reproduce.

**Comment by doitliketyler** [comment] 2022-10-03 17:56
1. No gif. I have a screenshot with the rewards messages but thats not going to help solve this.
2. https://pastebin.com/raw/VfwJGQtR
3. Server is only 2 days old and its been reported twice
4. CrateReloaded 2.1.4
5. Open a mysterycrate after receiving it as a reward from a keycrate

I imagine this is going to be difficult to reproduce because there are no error logs. I personally haven't be able to recreate it and was sent a screenshot of the multiple rewards given by a mysterycrate. Here is the config for one of the mystery crates: https://pastebin.com/raw/gZEBQAtL

Hope this helps. Also hope its something I did wrong but I can't find any mistakes so far.

**Comment by doitliketyler** [comment] 2022-10-04 00:04
Ok...we figured out the condition that causes it but not the why. This should at least point you in the right direction to start debugging. If a player is wearing leggings of any kind when opening a mystery crate this happens:

- They get rewarded
- The equipped leggings get moved to the main bar
- The mysterycrate gets moved to the leggings slot
- The player can then re-equip the leggings and use the mysterycrate again..infinitely

The mysterycrate only gets consumed when no leggings are equipped. Super bizarre but I've tested & confirmed it.

**Comment by imWillX** [comment] 2022-10-04 02:07
@doitliketyler I'm unable to reproduce using the instructions using the provided crate and a test server. This is the first time we're getting a report like this which makes me suspect it's another plugin. I'm available on discord to discuss this. Can you try reproducing using a vanilla server?

**Comment by doitliketyler** [comment] 2022-10-04 02:23
Ok well that's good to know. I'll need to setup a test server but yes I can do that and try and pinpoint the plugin causing this (fingers crossed). It may take a day or 2. I think I joined your Discord already so I can reach out on there when I have more info.

**Comment by imWillX** [comment] 2022-10-18 04:27
@doitliketyler Any updates?

**Comment by doitliketyler** [comment] 2022-10-21 00:04
Yes! Sorry it has taken so long. I was finally able to test this and discovered it was the AdvancedEnchantments plugin that was causing this to happen. I will be reporting the bug to that dev sometime tonight.

**Comment by imWillX** [comment] 2022-10-21 04:51
Thanks, will be closing the ticket.

**Closed by imWillX** 2022-10-21 04:51 UTC
