### ISSUE TITLE
/cr give to {player} "cratename" breaks the reward screen

### ISSUE THREAD

**Issue by ARchonSpigot** [Hazebyte/CrateReloaded#361] opened 2019-01-06 21:13 UTC
if you use /cr give to {player} "cratename" the reward screen breaks and you are stuck in it untill you are kicked, and can not open any more crates until the server is restarted.

Useful for giving a rare chance at some special crates

**Comment by imWillX** [comment] 2019-01-06 22:58
Which crate animation?
Error Log? 
Please provide a crate.yml

**Comment by imWillX** [comment] 2019-01-08 18:55
Closing. Unable to reproduce the issue.

**Closed by imWillX** 2019-01-08 18:55 UTC
