### ISSUE TITLE
Normal block function not canceled

### ISSUE THREAD

**Issue by Tyloon1e** [Hazebyte/CrateReloaded#491] opened 2020-10-10 14:00 UTC
When right-clicking too quickly on an item set as a Crate, the item event is not canceled - e.g. a chest would open as a normal chest after right-clicking twice very quickly on it. I also made a GIF with grindstones to document the issue: https://gyazo.com/6fa65b000c97a3be4b42e957525bbada
As far as I can tell, this happens with all blocks i.e. chests, ender chests, grindstones, potion stands, and so forth.

I'm running Paper 1.16.3, CrateReloaded (PRO) 20.0.32, WorldGuard 7.0.4.

**Comment by imWillX** [comment] 2020-11-02 07:45
@Tyloon1e There may be another plugin undoing our cancellation action. Could you contact me via discord to test it on a vanilla server?

**Comment by imWillX** [comment] 2020-11-05 07:35
Closing, unable to reproduce.

**Comment by imWillX** [comment] 2020-11-05 07:43
Actually, I forgot about our system that throttles listener calls. Currently if you click within 200 ms, it'll open the chest/etc.

You can disable this via the config. 
```
throttle:
  enabled: false
  speed: 200
```

**Closed by imWillX** 2020-11-05 07:43 UTC

**Comment by Tyloon1e** [comment] 2020-11-05 11:27
> Actually, I forgot about our system that throttles listener calls. Currently if you click within 200 ms, it'll open the chest/etc.
> 
> You can disable this via the config.
> 
> ```
> throttle:
>   enabled: false
>   speed: 200
> ```

I managed to add this under the "crate" key in config.yml without any errors when loading the plugin.
It doesn't seem to have any effect though, the throttle is still in place. It doesn't matter if it's enabled, disabled or what I set the speed to...

**Comment by imWillX** [comment] 2020-11-05 11:32
It should be a top level node, not under the crate.

**Comment by Tyloon1e** [comment] 2020-11-05 11:36
If I add it to the top level node and restart the server: https://pastebin.com/raw/PURcSHZc

**Comment by imWillX** [comment] 2020-11-05 11:39
I’ve updated the original code in the first comment.

**Comment by Tyloon1e** [comment] 2020-11-05 11:49
Working now. Thanks Will!
